import express from 'express'

const router = express.Router()

export default router

require('controllers/Auth/controller')
require('controllers/Role/controller')
require('controllers/User/controller')
require('controllers/Promo/controller')
require('controllers/Reservasi/controller')
require('controllers/Calendar/controller')
require('controllers/InformasiOrang/controller')
require('controllers/ReservasiKamar/controller')
require('controllers/Kamar/controller')
require('controllers/CheckAvailable/controller')
require('controllers/MasterSourcePemesanan/controller')
require('controllers/MasterStatusPemesanan/controller')
require('controllers/MasterTipeTamu/controller')
require('controllers/MasterStatusPembayaran/controller')
require('controllers/MasterJenisKelamin/controller')
require('controllers/MasterKewarganegaraan/controller')
require('controllers/MasterAgama/controller')
require('controllers/MasterOTA/controller')
require('controllers/MasterStatusPerkawinan/controller')
require('controllers/City/controller')
require('controllers/SpesifikasiKamar/controller')
require('controllers/InformasiCorporate/controller')
require('controllers/HargaSpesifikasiKamar/controller')
require('controllers/ItemKamar/controller')
require('controllers/MasterFungsiRuangan/controller')
require('controllers/MasterTipeRuangan/controller')
require('controllers/MasterSetupRuangan/controller')
require('controllers/ItemRuangan/controller')
require('controllers/Konsumsi/controller')
require('controllers/Linen/controller')
require('controllers/Amenity/controller')
require('controllers/VendorLaundry/controller')
require('controllers/Shift/controller')
require('controllers/MasterFasilitasTambahan/controller')
require('controllers/MasterTipePembayaran/controller')
require('controllers/EarlyCheckIn/controller')
require('controllers/LateCheckOut/controller')
require('controllers/MasterSpecialRequirement/controller')
require('controllers/MasterTipeKamar/controller')
require('controllers/MasterTipeKasur/controller')
require('controllers/MasterTipeIdentitas/controller')
require('controllers/MasterJenisPembayaran/controller')
require('controllers/Home/controller')
require('controllers/JenisFasiltiasTambahan/controller')
require('controllers/MasterStatusHK/controller')
require('controllers/MasterStatusTagihan/controller')
require('controllers/MasterTagihanKerusakanKehilangan/controller')
require('controllers/KerusakanKehilangan/controller')
require('controllers/Invoice/controller')
require('controllers/MasterItemPembayaran/controller')
require('controllers/RoomHK/controller')
require('controllers/LogRoomHK/controller')
require('controllers/ReservasiList/controller')
require('controllers/LinenListHk/controller')
require('controllers/LinenHk/controller')
require('controllers/ListAmenitiesHK/controller')
require('controllers/AmenityHK/controller')
require('controllers/LogInventory/controller')
require('controllers/LogLostAndFound/controller')
require('controllers/SimpleMaster/controller')
require('controllers/ProfileHotel/controller')
require('controllers/HakAkses/controller')
